                  ^|*|^                /
                  ^|*|^                /
sgjnl              \1/                 /
sgjnl                                  /
sgjnl                                  /
sgjnl                                  /
sgjnl                                  /
sgjnl                                  /
sgjnl                                  /
sgjnl                                  /
sgjnl                                  /
sgjnl                                  /
*                                      *
*                                      *
*                                      *
*                                      *
*                                      *
*                                      *
*                                      *
*                                      *
*                                      *
*                                      *
*                                      *
*                                      *
*                                      *
